export default {
  overview: {
    description: 'Even pirates, before they attack another ship, hoist a black flag. The Code is more like guidelines, really.',
    isOpen: true,
    suggestedDuration: 127,
    address: 'Jalan Tpj2 Taman Perindustrian Jaya, Subang Jaya, Selangor, 47200',
  },
  relativeRanking: [
    0,
    28,
  ],
  imageUrl: [
    'https://d3tteoxp56tq1d.cloudfront.net/images/tripadvisor_thailand_10.jpg',
    'https://d3tteoxp56tq1d.cloudfront.net/images/tripadvisor_thailand_13.jpg',
    'https://d3tteoxp56tq1d.cloudfront.net/images/tripadvisor_thailand_28.jpg',
    'https://d3tteoxp56tq1d.cloudfront.net/images/tripadvisor_thailand_63.jpg',
    'https://d3tteoxp56tq1d.cloudfront.net/images/tripadvisor_thailand_86.jpg',
    'https://d3tteoxp56tq1d.cloudfront.net/images/tripadvisor_thailand_66.jpg',
    'https://d3tteoxp56tq1d.cloudfront.net/images/tripadvisor_thailand_54.jpg',
    'https://d3tteoxp56tq1d.cloudfront.net/images/tripadvisor_thailand_7.jpg',
    'https://d3tteoxp56tq1d.cloudfront.net/images/tripadvisor_thailand_80.jpg',
    'https://d3tteoxp56tq1d.cloudfront.net/images/tripadvisor_thailand_87.jpg',
  ],
  _id: '6001f45dc6cc5d2005f7d2d7',
  attractionTitle: 'Sukhothai Old City',
  city: 'Samut Prakan, Thailand',
  ratio: 0,
  attractionType: 'Historic Sites',
  reviews: 2876,
  travelersChoiceAward: true,
  likedStatus: false,
  ticketPrice: 238,
  __v: 0,
};
